print("Welcome to Mad Libs!")
print("The goal of the game is to write down a word in a specific category.")
print("Then, the computer will fill up blank spaces of the story with your answers.")
print("Good Luck!")

Adj1 = input("Adjective?")
Adj2 = input("Adjective?")
Noun1 = input("Noun?")
Noun2 = input("Noun?")
PluralNoun1 = input("Plural noun?")
Game = input("Game?")
PluralNoun2 = input("Plural noun?")
Verbing1 = input("Verb ending in -ing?")
Verbing2 = input("Verb ending in -ing?")
Adj1 = input("Adjective?")
Verbing3 = input("Verb ending in -ing?")
PluralNoun3 = input("Plural noun?")
Noun3 = input("Noun?")
Plant = input("Plant?")
BodyPart = input("Part of the body?")
Place = input("Place?")
Verbing4 = input("Verb ending in -ing?")
Adj3 = input("Adjective?")
Number = input("Number?")
PluralNoun4 = input("Plural noun?")

print("A vacation is when you take a trip to some", Adj1,"place")
print("with your", Adj2,"family. Usually you go to some place")
print("that is near a/an", Noun1,"or up on a/an", Noun2)
print("A good vacation place is one where you can ride", PluralNoun1)
print("or play", Game," or go hunting for", PluralNoun2,". I like")
print("to spend my time", Verbing1,"or", Verbing2)
print("When parents go on a vacation, they spend their time eating")
print("three", PluralNoun3,"a day, and fathers play golf, and mothers")
print("sit around", Verbing3,". Last summer, my little brother")
print("fell in a/an", Noun3,"and got poison", Plant,"all")
print("over his", BodyPart," My family is going to go to (the)")
print(Place,", and I will practice", Verbing4,". Parents")
print("need vacations more than kids because parents are always very")
print(Adj3,"and because they have to work", Number)
print("hours every day all year making enough", PluralNoun4,"to pay")
print("for the vacation.")